### ISSUE TITLE
[Sample] ASPNETCORE MVC sample

### ISSUE THREAD

**Issue by ghost** [Aurochses/Aurochses.AspNetCore.Identity.SendGrid#6]
Hi @rodchenkov,

Please could you provide us with a sample of a aspnetcore mvc application with this implemented would greatly appreciate it.

**Comment by rodchenkov** [comment]
Hi

We are using it at this project: https://github.com/Aurochses/Aurochses.IdentityServer.Website

Hope this will help you and please let me know if you have any other questions.

**Comment by ghost** [comment]
Thank you @rodchenkov this repository is extremely helpful to me.
